Time_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('login.urls')),
    path('tracker/', include('tracker.urls')),
    path('admin/', admin.site.urls),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='login'),
    path('logged_in/', views.logged, name='logged')
]

login/models.py
from django.db import models

# Create your models here.


class Employee(models.Model):
    def __str__(self):
        return str(self.Username)

    Last_Name = models.CharField(max_length=100)
    First_Name = models.CharField(max_length=100)
    Username = models.CharField(max_length=50)
    Email_Address = models.EmailField(max_length=100)
    Password = models.CharField(max_length=100)
    Team = models.CharField(max_length=100)
    Active = models.BooleanField()

login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Employee


# renders the login screen
def index(request):
    return render(request, 'login/index.html')


# checks that the input username and password are correct
def logged(request):
    user = request.POST['in_user']
    password = request.POST['in_pass']
    # Check that the username is not in use
    for entry in Employee.objects.all():
        if entry.Username == user and entry.Password == password:
            return redirect('tracker:index', user=user)
    messages.error(request, 'Employee not found; make sure your employee information has been added to the database.')
    return redirect('login:login')





login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
    {% load static %}

    <link href="http://fonts.cdnfonts.com/css/ubuntu-mono" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'login/login.css' %}">
</head>
<body>
<div id="homepage">
    <div id="greeting" class="in_con">
        <h1>Welcome to the Employee Time-Tracker!</h1>
        <p>Track your hours - organize by project - analyze how your time was spent!</p>
        <p>All in one application!</p>
        <p>If you do not have a username and password (or if you've forgotten yours) contact the site administrator</p>
    </div>
    <div id="log" class="in_con">
        <form id="login" action="{% url 'login:logged' %}" method="post">
            {% csrf_token %}
            <h1>Log in</h1>
            <input type="text" maxlength="100" name="in_user" placeholder="Username" autocomplete="off"><br><br>
            <input type="password" maxlength="100" name="in_pass" placeholder="Password" autocomplete="off"
                   id="in_pass"><br>
            <br>
            <input type="checkbox" onclick="tog_pass()"><span>Show Password</span><br>
            <button type="submit">Log in</button>
        </form>
        <br>
        {% if messages %}
            {% for message in messages %}
                <p class="{{ message.tags }}">{{ message }}</p><br>
            {% endfor %}
        {% endif %}
    </div>
</div>

<script>
    function tog_pass() {
        var x = document.getElementById("in_pass");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }
</script>
</body>
</html>